### ISSUE TITLE
No mention about PMM chart being a "technological preview" in the official docs

### ISSUE THREAD

**Issue by gdubicki** [percona/percona-helm-charts#250]
Hi,

[This](https://github.com/percona/percona-helm-charts/blob/b26b54ecec3f629f41f88e4fa3323fb2910c0ec4/charts/pmm/README.md?plain=1#L3) mention is not repeated in the official docs [here](https://docs.percona.com/percona-monitoring-and-management/setting-up/server/helm.html).

Please make it consistent.

**Comment by spron-in** [comment]
Hey @gdubicki, 

sorry, this sat here for some time without a response. Helm chart is GA. Sent a PR to fix it in the readme.
Thank you for spotting it.
