### ISSUE TITLE
Helm values for mongo db helm charts should allow override of individual replicaset configurations ,like size ,requests, limits etc 

### ISSUE THREAD

**Issue by spron-in** [percona/percona-helm-charts#264]
Copying it from roadmap project.

Current helm values file for mongo db uses array structure for configuring replica sets . This will be difficult to override using the helm --set option as it will override the entire array options .Please refer the recommended way i.e, using maps [here](https://helm.sh/docs/chart_best_practices/values/#:~:text=For%20this%20reason%2C%20it%27s%20often%20better%20to%20structure%20your%20values%20file%20using%20maps.). Helm charts should allow override of individual replica set configurations.
current configuration for replsets is as below
replsets:

```
name: rs0
size: 3
affinity:
affinityEnabled: true
advanced:
nodeAffinity:
reqdForSchIgnForExec:
nodeSelTerms:
matchExpr:
```
It can be made
```
replsets:
rs0:
size: 3
affinity:
affinityEnabled: true
advanced:
nodeAffinity:
reqdForSchIgnForExec:
nodeSelTerms:
matchExpr:
```
This will be very useful in overriding default configurations in helm using deployment tools like porter

**Comment by aleksasiriski** [comment]
+1 for this, it would be very useful
