### ISSUE TITLE
Pod doesn't start with pg-operator v2.3.0 with `watchAllNamespaces: true` set: `panic: WATCH_NAMESPACE must be set`

### ISSUE THREAD

**Issue by scottaubrey** [percona/percona-helm-charts#275]
# Description

Upgrading `pg-operator` helm chart from v2.2.2 to v2.3.0 resulting in pod crashing. The only value in place is `watchAllNamespaces: true`

This appears to be related to changes to the operator that make `WATCH_NAMESPACE` environment variable mandatory as the pod starts and crashes straight away:
```
> kubectl logs -n db-operator-system   pg-operator-7bbb8cc449-9bp5q
2024-01-05T08:10:03.804Z	INFO	feature gates enabled	{"PGO_FEATURE_GATES": "TablespaceVolumes=false,BridgeIdentifiers=false,InstanceSidecars=true,PGBouncerSidecars=false,AllAlpha=false,AllBeta=false"}
panic: WATCH_NAMESPACE must be set

goroutine 1 [running]:
main.assertNoError(...)
	/go/src/github.com/percona/percona-postgresql-operator/cmd/postgres-operator/main.go:53
main.main()
	/go/src/github.com/percona/percona-postgresql-operator/cmd/postgres-operator/main.go:118 +0x78d
```

Looking at the template, it looks like that env var is excluded when `watchAllNamespaces: true`. The log message above would suggest it's now required, so the helm chart is capable of creating an invalid deployment with this version of pg-operator.

**Comment by tplavcic** [comment]
Thanks for the report! The issue is now fixed and available in pg-operator chart version `2.3.1`.
