### ISSUE TITLE
PXC-operator update to K8SPXC-1274

### ISSUE THREAD

**Issue by grzegorzgniadek** [percona/percona-helm-charts#289]
Hi,
i would like to know or ask how can i deploy merged https://github.com/percona/percona-xtradb-cluster-operator/pull/1507 into my pxc-operator running on kubernetes cluster. As i see new 1.13.5 does not contain https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-operator/crds/crd.yaml that changes.

**Comment by tplavcic** [comment]
You cannot with helm charts out of the box (technically you can clone the chart, copy crd and change docker images), but you can also do it from our operator "main" branch without helm chart - but all this is not recommended for production.

**But we will have a 1.14.0 release in a week or so and the helm chart will be updated as well, so I would suggest to just wait.**

**Comment by grzegorzgniadek** [comment]
Thank you very much for fast answer and opportunity to use this awesome operator.
