### ISSUE TITLE
pg-db - Syntax issue while helm install 

### ISSUE THREAD

**Issue by TAbhay** [percona/percona-helm-charts#305]
While setting up secret in backups, it's not able to detect the secret 'pg-backup-secret' while helm install.

Issue:
![issue](https://github.com/percona/percona-helm-charts/assets/56065895/73e08f1c-b99f-4c59-b0bb-7103acfcd9ab)

Fix:
Syntax needs to be changed in values.yaml
![fix-](https://github.com/percona/percona-helm-charts/assets/56065895/9f8c61df-c00c-428e-a840-515b57d74694)

**Comment by TAbhay** [comment]
Raised Pull request : https://github.com/percona/percona-helm-charts/pull/313
@tplavcic  Please review it. 
Thank you. 🙂

**Comment by tplavcic** [comment]
The PR is merged (with some changes) so this should be fixed now.
