### ISSUE TITLE
PMM Client Helm Chart

### ISSUE THREAD

**Issue by misterek** [percona/percona-helm-charts#315]
Is there a helm chart for PMM Client?  We have some environments with RDS databases, and would like to try out PMM, but our infrastructure is exclusively kubernetes. Is there a helm chart for this?

**Comment by rnovikovP** [comment]
@misterek, can you elaborate more on your use case? As for  RDS monitoring - you don't need the PMM Client. You need some API to add RDS to PMM.
The RDS monitoring is happening from the PMM server itself.

**Comment by misterek** [comment]
Hm, well, it turns out that there's a very real chance that I have no idea what I'm talking about :) 

I guess I read this line "In this case, the PMM Client is not installed on the host where the database server is deployed." as "It needs to be deployed somewhere else", not "That it's monitored from the server itself".

So... that may have just solved all of my problems :). Thank you!  I'll close this now as well since it, you know, makes no sense :)
